"use client";
import { useEffect, useState } from "react";
import {
  ActionMenu, Badge, Button, Card, CardBody, CardFooter, CardHeader, Checkbox, ClickableCard,
  Combobox, ConfirmDialog, CurrencyInput, DataTable, DateInput, EmptyState, Field, Input, Link,
  NumberInput, PageActionBar, PercentageInput, ProgressBar, Radio, Select, Skeleton, Spinner, Switch,
  Tabs, Textarea, Toast,
} from "../index";
import { Archive, Calculator, Copy, Plus, Save, Trash2 } from "../icons";

const buttonVariants = ["primary", "secondary", "tertiary", "destructive", "success", "ghost", "link"] as const;
export function DesignSystemShowcase() {
  const [ready, setReady] = useState(false);
  const [tab, setTab] = useState("components"); const [modal, setModal] = useState(false); const [toast, setToast] = useState(false);
  const [switchValue, setSwitchValue] = useState(true); const [combo, setCombo] = useState("cmp");
  useEffect(() => setReady(true), []);
  return <main className="ds-showcase" data-ready={ready ? "true" : "false"}>
    <PageActionBar eyebrow="TH OS · DS-001" title="Design System" breadcrumb={<Link href="/" variant="subtle">TH OS / Desenvolvimento</Link>} status={<Badge tone="experimental">Somente desenvolvimento</Badge>} primaryAction={<Button variant="primary" icon={Save} onClick={() => setToast(true)}>Salvar exemplo</Button>} secondaryActions={<Button variant="secondary" icon={Calculator}>Calcular</Button>} />
    <Tabs ariaLabel="Seções do showcase" value={tab} onChange={setTab} items={[{ id: "components", label: "Componentes" }, { id: "tokens", label: "Tokens" }, { id: "guidance", label: "Uso correto" }]} />
    {tab === "components" ? <div className="ds-showcase__sections">
      <Showcase title="Botões" description="Sete variantes, três alturas, ícones, loading, focus e disabled."><div className="ds-showcase__row">{buttonVariants.map((variant) => <Button key={variant} variant={variant} icon={variant === "primary" ? Calculator : undefined}>{variant}</Button>)}</div><div className="ds-showcase__row"><Button size="small">small</Button><Button size="medium">medium</Button><Button size="large">large</Button><Button loading>Carregando</Button><Button disabled>Desabilitado</Button></div></Showcase>
      <Showcase title="Campos" description="Labels persistentes, ajuda e erro sem depender de placeholder."><div className="ds-showcase__grid"><Field label="Nome" htmlFor="ds-name" helpText="Identificação interna"><Input id="ds-name" defaultValue="Projeto residencial" /></Field><Field label="Valor" htmlFor="ds-money"><CurrencyInput id="ds-money" defaultValue="2.000,00" /></Field><Field label="Percentual" htmlFor="ds-percent"><PercentageInput id="ds-percent" defaultValue="40" /></Field><Field label="Quantidade" htmlFor="ds-number"><NumberInput id="ds-number" defaultValue="2" /></Field><Field label="Data" htmlFor="ds-date"><DateInput id="ds-date" /></Field><Field label="Status" htmlFor="ds-select"><Select id="ds-select" defaultValue="draft"><option value="draft">Rascunho</option><option value="approved">Aprovado</option></Select></Field><Field label="Observações" htmlFor="ds-notes"><Textarea id="ds-notes" /></Field><Field label="Campo inválido" htmlFor="ds-invalid" errorText="Revise este valor"><Input id="ds-invalid" invalid defaultValue="Inválido" /></Field></div><div className="ds-showcase__row"><Checkbox label="Incluir no escopo" defaultChecked /><Radio label="Opção selecionada" defaultChecked /><Switch label="Ativo" checked={switchValue} onChange={setSwitchValue} /></div><Combobox label="Módulo" value={combo} onChange={setCombo} options={[{ value: "cmp", label: "CMP-001" }, { value: "cap", label: "CAP-001" }, { value: "hon", label: "HON-001" }]} /></Showcase>
      <Showcase title="Cards, badges e ações" description="Cards estáticos não imitam ações; cards clicáveis respondem a teclado."><div className="ds-showcase__grid"><Card><CardHeader><h3>Card estático</h3></CardHeader><CardBody><p>Conteúdo informativo sem cursor de ação.</p><Badge tone="success">Aprovado</Badge></CardBody><CardFooter><Button variant="secondary" icon={Copy}>Duplicar</Button></CardFooter></Card><ClickableCard title="Abrir projeto" description="Hover, foco, cursor e Enter/Space" onActivate={() => setToast(true)} /><ActionMenu items={[{ label: "Duplicar", icon: Copy, onSelect: () => setToast(true) }, { label: "Arquivar", icon: Archive, onSelect: () => setToast(true) }, { label: "Excluir", icon: Trash2, destructive: true, onSelect: () => setModal(true) }]} /></div></Showcase>
      <Showcase title="Tabela e feedback" description="Tabela vira cards no celular; feedback usa semântica e aria-live."><DataTable caption="Valores de exemplo" rows={[{ id: "1", name: "Projeto arquitetônico", value: "R$ 12.000,00" }, { id: "2", name: "Interiores", value: "R$ 4.000,00" }]} rowKey={(row) => row.id} columns={[{ key: "name", header: "Serviço", cell: (row) => row.name }, { key: "value", header: "Valor", cell: (row) => row.value, numeric: true }]} /><div className="ds-showcase__row"><Spinner /><Skeleton style={{ width: 180 }} /><ProgressBar label="Progresso" value={68} /><Button variant="destructive" icon={Trash2} onClick={() => setModal(true)}>Abrir confirmação</Button></div></Showcase>
      <Showcase title="Estado vazio"><EmptyState title="Nenhum cenário" description="Crie o primeiro cenário para comparar valores." action={{ children: "Criar cenário", icon: Plus, onClick: () => setToast(true) }} /></Showcase>
    </div> : tab === "tokens" ? <Showcase title="Tokens"><div className="ds-token-grid">{["brand-military", "brand-military-hover", "brand-military-dark", "color-bg", "color-surface", "color-border", "color-text", "color-text-muted", "color-success", "color-warning", "color-error", "color-info"].map((token) => <div key={token}><span style={{ background: `var(--${token})` }} /><code>--{token}</code></div>)}</div></Showcase> : <Showcase title="Uso correto"><div className="ds-guidance"><article className="is-correct"><h3>Correto</h3><Button variant="primary" icon={Calculator}>Calcular honorários</Button><p>Uma ação primária clara, com verbo, borda, contraste e feedback.</p></article><article className="is-incorrect"><h3>Evitar</h3><span className="ds-bad-button-example">calcular</span><p>Texto colorido sem semântica, área clicável ou estados.</p></article></div></Showcase>}
    <ConfirmDialog open={modal} title="Excluir exemplo?" description="Esta ação demonstra foco preso, Escape e hierarquia destrutiva." confirmLabel="Excluir exemplo" confirmVariant="destructive" onConfirm={() => setToast(true)} onClose={() => setModal(false)} />
    {toast ? <Toast variant="success" title="Ação concluída" message="O usuário recebeu retorno visual e semântico." onClose={() => setToast(false)} /> : null}
  </main>;
}
function Showcase({ title, description, children }: { title: string; description?: string; children: React.ReactNode }) { return <section className="ds-showcase__section"><header><h2>{title}</h2>{description ? <p>{description}</p> : null}</header>{children}</section>; }
